### ISSUE TITLE
sensor access

### ISSUE THREAD

**Issue by anatolysukhanov** [jchomko/a-heart-from-space#1]
Ensure sensor access works across all generations of smartphone - I've been seeing issues with accessing some of the newest iPhones

**Comment by jchomko** [comment]
I think this issue is mainly in iOS 13 + devices. The existing code should request sensor access from the browser but doesn't seem to be doing this, and I haven't had access to a device to test.

**Comment by anatolysukhanov** [comment]
iPhone 8, iOS 13.5.1, Safari:

1. I click OK twice

![b3c17aee-1adb-4fb6-b570-249f4cf407b5](https://user-images.githubusercontent.com/7021042/87987141-cdaa4b80-cae6-11ea-9bac-32083ff90065.jpg)

![81714dbd-78b0-423e-a775-f0b241fc7bda](https://user-images.githubusercontent.com/7021042/87987171-d733b380-cae6-11ea-81b6-ea237afbc848.jpg)

2. I click "Center Map" and then I see my location as the blue drop

![10bd2a34-0acc-468b-8397-f6383ad2a6c7](https://user-images.githubusercontent.com/7021042/87987177-dac73a80-cae6-11ea-9ac8-060680f58840.jpg)

Where did it stop working from your experience?

**Comment by jchomko** [comment]
The issue was that the blue dot wasn't rotating with the compass - though it does look like it's asking for compass permission. I haven't been able to test this myself as I don't have a device running iOS 13.

**Comment by anatolysukhanov** [comment]
> The issue was that the blue dot wasn't rotating with the compass - though it does look like it's asking for compass permission.

The error is this:

"NotAllowedError: Requesting device orientation or motion access requires a user gesture to prompt"

Here is an explanation:

https://stackoverflow.com/a/56764762/5602923

**Comment by jchomko** [comment]
Ah okay - that's why I had the first modal in there, to act as user gesture, but I guess it doesn't register?

**Comment by anatolysukhanov** [comment]
> Ah okay - that's why I had the first modal in there, to act as user gesture, but I guess it doesn't register?

It does register.

"NotAllowedError: Requesting device orientation or motion access requires a user gesture to prompt" comes from  .catch in DeviceOrientationEvent.requestPermission()

It works though if I wrap it in a function and call it from a button click handler.

**Comment by anatolysukhanov** [comment]
I would imagine confirm doesn't count as user gesture.

**Comment by jchomko** [comment]
Great that it works by wrapping it in a function! Can you push the update so I can test locally? I got a phone that can run iOS 13 now.

**Comment by anatolysukhanov** [comment]
> Great that it works by wrapping it in a function! Can you push the update so I can test locally? I got a phone that can run iOS 13 now.

Done. Please check it out.

**Comment by jchomko** [comment]
Ok thanks, just tested! I'm not getting any rotation on the blue drop, but not seeing any errors either. Were you getting the rotation?

**Comment by anatolysukhanov** [comment]
> I'm not getting any rotation on the blue drop, but not seeing any errors either. Were you getting the rotation?

I was, but it must have been cached.

Calling requestDeviceOrientation from confirm doens't have the effect. It should be called from a click event handler like center().

**Comment by anatolysukhanov** [comment]
![b538470c-787d-4074-949e-878254f215f1](https://user-images.githubusercontent.com/7021042/88348515-4fec7700-cd56-11ea-8380-82f8924f09de.jpg)

**Comment by jchomko** [comment]
Ok super, works now!
